config/routes.rb
Switchboard::Application.routes.draw do
  resources :members, except: :show

  resources :messages, only: [:index]

  resources :entries, only: [:create, :index]

  get "wemo", to: "wemo#show"

  root to: 'entries#index'
end

app/models/entry.rb
require 'rest-client'

class Entry < ActiveRecord::Base
  belongs_to :member

  ACTIONS = {
    'lock'   => /\A\s*l(ock)?/i,
    'unlock' => /\A\s*(u|i)(nlock)?/i
  }

  before_validation :extract_action
  validates :action, inclusion: {in: ACTIONS.keys}
  after_create :notify!

  def self.actions
    ACTIONS.keys
  end

  def self.by_day
    includes(:member).order(created_at: :desc).limit(100).group_by do |entry|
      entry.created_at.in_time_zone("Eastern Time (US & Canada)").to_date
    end
  end

  def unlock?
    extract_action == 'unlock'
  end

  def lock?
    extract_action == 'lock'
  end

  private

  def extract_action
    self.action ||= ACTIONS.find { |_, regex| body =~ regex }.try :first
  end

  def notify!
    RestClient.post "http://#{ENV["DOOR_USER"]}:#{ENV["DOOR_TOKEN"]}@#{ENV["DOOR_URL"]}/api/device/CoworkBuffalo?state=blink&delay=4", {}
  end
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :entries

  phony_normalize :phone_number, default_country_code: 'US'
  validates :phone_number, phony_plausible: true, presence: true
  validates :name, presence: true

  def self.find_from_number!(number)
    find_by_phone_number! PhonyRails.normalize_number(number)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def self.require_authentication!(options = {})
    http_basic_authenticate_with options.merge(name: "coworkbuffalo", password: Switchboard.admin_password)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  require_authentication! except: :create
  protect_from_forgery except: :create
  before_filter :verify_token, only: :create

  def create
    @member = Member.find_from_number!(params[:From])
    @entry = @member.entries.new(body: params[:Body])
    @entry.save
    respond_to(&:xml)
  end

  def index
    @entries_by_day = Entry.by_day
  end

  private

    def verify_token
      render nothing: true, status: :unauthorized if params[:token] != Switchboard.twilio_token
    end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  require_authentication!

  before_action :set_member, only: [:edit, :update, :destroy]

  def index
    @members = Member.all
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  def create
    @member = Member.new(member_params)

    if @member.save
      redirect_to members_url, notice: 'Member was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /members/1
  def update
    if @member.update(member_params)
      redirect_to members_url, notice: 'Member was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /members/1
  def destroy
    @member.destroy
    redirect_to members_url, notice: 'Member was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = Member.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def member_params
      params.require(:member).permit(:name, :phone_number)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  require_authentication!

  def index
    @messages = Switchboard.twilio_client.account.messages.list
  end
end

app/controllers/wemo_controller.rb
class WemoController < ApplicationController
  require_authentication!

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link_to(name, path)
    options = {}
    options[:class] = "active" if controller.class.name.downcase.include?(name.downcase)

    link_to name, path, options
  end

  def easternify(date, format)
    date.in_time_zone("Eastern Time (US & Canada)").to_formatted_s(format)
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/entries/create.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Message>
    <% if @entry.unlock? %>
      The door will unlock in a moment! Please open the door when you hear it click. Welcome back to CoworkBuffalo, <%= @member.name %>!
    <% elsif @entry.lock? %>
      Thanks for visiting CoworkBuffalo! The door is now locked.
    <% else %>
      Sorry, I didn't understand that. Please send another SMS with one of the following choices: <%= Entry.actions.join(', ') %>
    <% end %>
  </Message>
</Response>

app/views/entries/index.html.erb
<section class="entries">
  <% @entries_by_day.each do |date, entries| %>
    <h2><%= date.to_formatted_s(:long) %></h2>
    <% entries.each do |entry| %>
      <p>
        <strong><%= easternify(entry.created_at, :time) %></strong>: <%= entry.member.name %> <%= entry.action %>ed the door.
      </p>
    <% end %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Switchboard</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="main">
    <ul>
      <li><%= link_to "Home", root_path, class: "home" %></li>
      <li><%= nav_link_to "Entries", entries_path %></li>
      <li><%= nav_link_to "Members", members_path %></li>
      <li><%= nav_link_to "Messages", messages_path %></li>
      <li><%= nav_link_to "WeMo", wemo_path %></li>
    </ul>
  </nav>
<%= yield %>
</body>
</html>

app/views/members/_form.html.erb
<%= form_for(@member) do |f| %>
  <% if @member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% @member.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= button_to 'Remove Member', @member, method: :delete, data: { confirm: 'Are you sure?' } unless @member.new_record? %>

app/views/members/edit.html.erb
<section class="members">
  <%= render 'form' %>
</section>

app/views/members/index.html.erb
<nav class="actions">
  <%= link_to 'New Member', new_member_path %>
</nav>

<section class="members">
  <table>
  <% @members.each do |member| %>
    <tr>
      <td>
        <%= link_to member.name, edit_member_path(member) %>
      </td>
      <td>
        <%= link_to member.phone_number.phony_formatted(spaces: '-'), edit_member_path(member) %>
      </td>
    </tr>
  <% end %>
  </table>
</section>

app/views/members/new.html.erb
<section class="members">
  <%= render 'form' %>
</section>

app/views/messages/create.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Message>
    <% if @knock.unlock? %>
      The door will unlock in a moment! Please open the door when you hear it click. Welcome to CoworkBuffalo, <%= @member.name %>!
    <% elsif @knock.lock? %>
      Thanks for visiting CoworkBuffalo! The door is now locked.
    <% else %>
      Sorry, I didn't understand that. Please send another SMS with one of the following choices: <%= Knock::TAGS.join(', ') %>
    <% end %>
  </Message>
</Response>

app/views/messages/index.html.erb
<section class="messages">
  <table>
    <tr>
      <th>Date</th>
      <th>From</th>
      <th>To</th>
      <th>Status</th>
      <th>Body</th>
    </tr>
  <% @messages.each do |message| %>
    <tr>
      <td>
        <%= easternify(DateTime.parse(message.date_sent), :short) %>
      </td>
      <td>
        <%= message.from.phony_formatted(spaces: '-') %>
      </td>
      <td>
        <%= message.to.phony_formatted(spaces: '-') %>
      </td>
      <td>
        <%= message.status %>
      </td>
      <td>
        <%= message.body %>
      </td>
    </tr>
  <% end %>
  </table>
</section>

app/views/wemo/show.html.erb
<section class="wemo">
  <iframe width='100%' height='500' frameborder='0' src='<%= ENV['WEMO_EMBED_LINK'] %>'></iframe>
</section>